# Paltas de CC de Sammy Arias

### Librerias

In [198]:
import math
import time
import inspect
import numpy as np
from scipy import linalg
import ipywidgets as widgets
from ipywidgets import interact, fixed
from matplotlib import pyplot as plt
%matplotlib inline

In [105]:
lam = np.diag(np.arange(1,11,1))
np.random.seed(739)
mV,_ = np.linalg.qr(np.random.random((10,10)))
ma = mV.dot(lam.dot(mV.T))

# Valores y vectores propios

## Power Iteration

In [106]:
def power_iteration(A, x, k):
    for i in range(k):
        u = x/np.linalg.norm(x)
        x = np.dot(A, u)
        lam = np.dot(u.T, x) 
    u = x/np.linalg.norm(x)
    return (lam, u)

In [107]:
power_iteration(ma,np.ones((10,1)),100)

(array([[9.99999999]]),
 array([[-0.14586551],
        [ 0.19100024],
        [ 0.19127136],
        [ 0.10987366],
        [ 0.12118704],
        [ 0.50347803],
        [-0.34801216],
        [ 0.10513663],
        [ 0.06362824],
        [-0.69942409]]))

## Inverse Power Iteration

In [98]:
def inverse_power_iteration(A, x, s, k):
    As = A - s*np.eye(*A.shape)
    for i in range(k):
        u = x/np.linalg.norm(x)
        x = np.linalg.solve(As, u)
        lam = np.dot(u.T, x)
    u = x/np.linalg.norm(x)
    return (1./lam+s, u)

In [99]:
inverse_power_iteration(ma,np.ones((10,1)),0,100)

(array([[1.]]),
 array([[0.39899009],
        [0.40884081],
        [0.43570072],
        [0.41839804],
        [0.11357094],
        [0.1112547 ],
        [0.0998296 ],
        [0.06011853],
        [0.41664417],
        [0.31034747]]))

## Rayleigh Quotient Iteration

In [120]:
def rqi(A, x, k):
    for i in range(k):
        u = x/np.linalg.norm(x)
        lam = np.dot(u.T, np.dot(A, u))
        try:
            print(lam)
            x = np.linalg.solve(A -lam*np.eye(*A.shape), u)
        except numpy.linalg.LinAlgError:
            break
    u = x/np.linalg.norm(x)
    lam = float(np.dot(u.T, np.dot(A, u)))
    return (lam, u)

In [121]:
rqi(ma,np.ones((10,1)),100)

[[1.53977543]]
[[1.19914012]]
[[1.01412855]]
[[1.00000293]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]
[[1.]]


(0.9999999999999998,
 array([[0.39899009],
        [0.40884081],
        [0.43570072],
        [0.41839804],
        [0.11357094],
        [0.1112547 ],
        [0.0998296 ],
        [0.06011853],
        [0.41664417],
        [0.31034747]]))

## Normalized Simultaneous Iteration

In [122]:
def normalized_simultaneus_iteration(A,Q,k):
    for i in range(k):
        Q,R = np.linalg.qr(A.dot(Q))
    iv = np.diag(Q.T.dot(A.dot(Q)))
    return iv

In [123]:
normalized_simultaneus_iteration(ma,np.eye(10),100)

array([9.99999999, 9.00000001, 8.        , 7.        , 6.        ,
       5.        , 4.        , 3.        , 2.        , 1.        ])

## Unshifted QR algorithm

In [124]:
def unshifted_QR_algorithm(R,Q,k):
    Q_a = Q
    for i in range(k):
        Q,R = np.linalg.qr(R.dot(Q))
        Q_a = Q_a.dot(Q)
    iv = np.diag(R.dot(Q))
    return iv

In [125]:
unshifted_QR_algorithm(ma,np.eye(10),100)

array([9.99999999, 9.00000001, 8.        , 7.        , 6.        ,
       5.        , 4.        , 3.        , 2.        , 1.        ])

# Integracion numerica

## Sumas de Riemann

In [162]:
def riemann(fun, N, a, b, direction='izq'):
    f = np.vectorize(fun)
    x = np.linspace(a, b, N)
    dx = x[1]-x[0]
    if(direction=='izq'):
        puntos = x[:-1]
    elif(direction=='der'):
        puntos = x[1:]
    else:
        print('direccion incorrecta')
        exit()
    int_val = (dx*f(puntos)).sum()
    return int_val

In [163]:
riemann(lambda x:x**2,100,1,5)

40.84957317280554

## Regla del Punto Medio

In [167]:
def punto_medio(fun,N,a,b):
    f = np.vectorize(fun)
    x = np.linspace(a,b,N)
    dx = x[1] - x[0]
    int_val = (dx*f(x[:-1]+0.5*dx)).sum()
    return int_val

In [168]:
punto_medio(lambda x:x**2,100,1,5)

41.33278917117305

## Regla del Trapecio

In [160]:
def metodo_del_trapecio(fun,N,a,b):
    f = np.vectorize(fun)
    x = np.linspace(a,b,N)
    dx = x[1]-x[0]
    int_val = (0.5*dx*(f(x[:-1])+f(x[1:]))).sum()
    return int_val

In [161]:
metodo_del_trapecio(lambda x:x**2,100,1,5)

41.33442165765403

## Regla de Simpson

In [170]:
def simpsons(fun, N, a, b):
    if N%2==1:
        print("Simpsons rule only applicable to even number of segments")
        return None
    x = np.linspace(a, b, N+1)
    dx = x[1]-x[0]
    xleft = x[:-2:2]
    xmiddle = x[1::2]
    xright = x[2::2]
    int_val = (dx/3) * sum( f(xleft) + 4*f(xmiddle) + f(xright) )
    return int_val

In [171]:
simpsons(lambda x:x**2,100,1,5)

41.33333333333337

## Cuadratura Gaussiana

In [188]:
def gaussianquad(fun, N, a, b):
    x, w = gaussian_nodes_and_weights(N,a,b)
    int_val = sum( w * fun(x) )
    return int_val
def gaussian_nodes_and_weights(N, a, b):
    if N==1: 
        return np.array([1]), np.array([2])
    beta = .5 / np.sqrt(1.-(2.*np.arange(1.,N))**(-2))
    T = np.diag(beta,1) + np.diag(beta,-1)
    D, V = np.linalg.eigh(T)
    x = D
    x = .5 * ( (b-a)*x + b + a) # Rescaling
    w = 2*V[0,:]**2
    w = .5*(b-a)*w
    return x, w

In [189]:
gaussianquad(lambda x:x**2,100,1,5)

41.33333333333332

In [202]:
interact(power_iteration,A=fixed(ma),x=fixed(np.ones((10,1))),k=widgets.IntSlider(min=1, max=200, step=1, value=5))

interactive(children=(IntSlider(value=5, description='k', max=200, min=1), Output()), _dom_classes=('widget-in…

<function __main__.power_iteration(A, x, k)>

### Numpy

In [190]:
#np.arange() #https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html
#np.dot() #https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html
#np.eye() #https://docs.scipy.org/doc/numpy/reference/generated/numpy.eye.html
#np.diag() #https://docs.scipy.org/doc/numpy/reference/generated/numpy.diag.html
#np.vectorize() #https://docs.scipy.org/doc/numpy/reference/generated/numpy.vectorize.html

#np.random.seed() #https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.seed.html
#np.random.random() #https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.random.html

#np.linalg.norm() #https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.norm.html
#np.linalg.qr() #https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.qr.html
#np.linalg.eig() #https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.eig.html
#np.linalg.solve() #https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.linalg.solve.html

### Scipy

In [ ]:
#sparse matrix  #https://docs.scipy.org/doc/scipy/reference/sparse.html

### ipywidgets

In [ ]:
#interact() #https://ipywidgets.readthedocs.io/en/latest/examples/Using%20Interact.html